proxies:
  - &p1
    name:
    address:
  - &p2
    name:
    address:

users:
  - username:
    password:
    proxy:

  - username:
    password:
    proxy: *p1

  - username:
    password:
    proxy: *p2

